services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=trading'
      - 'POSTGRES_PASSWORD=trading'
      - 'POSTGRES_USER=trading'
    ports:
      - '5432:5432'
    volumes:
      - 'postgres_data:/var/lib/postgresql'

  kafka:
    image: apache/kafka:latest
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093

      - KAFKA_LISTENERS=INTERNAL://:9092,EXTERNAL://:9094,CONTROLLER://:9093
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL

      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_CLUSTER_ID=KRaftClusterId123456789012
    ports:
      - "9094:9094"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - kafka
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/trading'
      - 'SPRING_DATASOURCE_USERNAME=trading'
      - 'SPRING_DATASOURCE_PASSWORD=trading'
      - 'SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092'
    ports:
      - '8080:8080'

volumes:
  postgres_data:
